### ISSUE TITLE
Create knz research locations

### ISSUE THREAD

**Issue by yxia326** [lter/deims-knz-custom#11]
I have all the latitude and longitude excel files ready for knz research stations, need to create the images

**Comment by isangil** [comment]
okay, here is a plan:
watersheds seem to be the most prevalent denominator when it comes to cite places of research.  while there are other more fine grained locations, the actual points would lack some remarkable identity.  let's then use watershed.

from the KML files, extract the 50 some names for polygons and watersheds, and see whether we can automatically (migrate CSV framework) create a bunch of them.  later, we will associate the datasets with the research sites, and also, add a view in lieu of the node-rendering.  then we will be done (in route, we will add a dynamic map of watersheds, etc)

**Comment by isangil** [comment]
done with a couple of shenanigans -- first, perl to massage the gis-data into WKT, then class to mass-import see https://github.com/lter/deims-knz-custom/commit/90d9401ca096c9852e7a5fd2da05fff9eb753832
