### ISSUE TITLE
Publication page need to upload new files

### ISSUE THREAD

**Issue by yxia326** [lter/deims-knz-custom#13]
Publication page need to upload new files: since I have done lots of records cleansing in the database, eg: the order of authors, add doi,

**Comment by isangil** [comment]
Are these additional records, or are these records that were already imported, but we want to re-import again?

**Comment by yxia326** [comment]
New additional records, I may need to remove all the old records, then
import new files,  the old records with no doi assigned.

**Comment by isangil** [comment]
this is done
